[package]
name = "gfx-gtk"
version = "0.1.0"
authors = ["Nicola Orru <nigu.orru@gmail.com>"]
edition = "2018"

[[bin]]
name="gfx-gtk"
path="src/main.rs"

[[bin]]
name="glarea"
path="src/glarea.rs"


[dependencies]
libc = "*"
epoxy = "0.0.4"
shared_library = "*"
glium = "*"
gl = "*"
glutin = "*"
gtk = { version = "*", features=["v3_16"] }
gdk = { version = "*", features=["v3_16"] }
gfx = "0.17"
gfx_core = "0.8"
gfx_device_gl = "0.15"

# gfx_window_glutin = { version = "*", path="../gfx_window_glutin" }